### ISSUE TITLE
useBid not returning any data

### ISSUE THREAD

**Issue by sammdec** [public-assembly/builder-utils#88]
Ive just updated to 0.0.33 and notiuced that `useBid`, is not returning anything from the hook. Looking at the code it looks as thought the code has been explicitly commented out. Is there are reason and if so is there an alternative hook to get bids data?

**Comment by sammdec** [comment]
@salieflewis Ah gotcha! no worries, i have rolled back to 0.0.31. Im working with the Gemma team and we are building a custom nouns builder dao auction site and using flexible as a guide.

**Comment by salieflewis** [comment]
Ahh werd! That is dope. I'll share updates with you as soon as I get this figured out.

**Comment by salieflewis** [comment]
@sammdec Just did a minor bump, so we're at 0.1.0 now. The bump introduces a ton of breaking changes, so depending on how far along you are with the build, it may not make sense to catch up. But basically I wasn't able to figure out how to continue using wagmi inside the package, so everything got stripped down to viem. 

The sandbox inside the monorepo is where I'll being building out the tutorial that shows folks how to create an auction component with the version of builder-utils. Happy to chat more throughly about any of this if you have questions!
